### PR TITLE
Dump cluster state on test failures

### PR DESCRIPTION
**Pull request by orenc1**
To easily get the reason for deployment / upgrade failures.

Signed-off-by: orenc1 <ocohen@redhat.com>

### CODE REVIEW

**Comment by orenc1** [comment]
Hi @dhiller , could you please add Simone to openshift-cnv org members?
Or is it done via peribolos for this org as well?

**Comment by dhiller** [comment]
> Hi @dhiller , could you please add Simone to openshift-cnv org members?
> Or is it done via peribolos for this org as well?

No, cnv-ci is currently managed manually.  But this is a good point. I'm looking into adding this to peribolos currently.

https://github.com/kubevirt/project-infra/pull/1461

**Comment by orenc1** [comment]
CNV 2.6.5 is not supported to be installed on OCP 4.9, due to deprecated APIs.
skipping this lane for now, until CNV 4.8.0 is GA'ed.

/override ci/prow/4.9-e2e-upgrade

**Pull request merged**
