### PR TITLE
Enable tests for 4.14

### PR DESCRIPTION
**Pull request by rabin-io**
Resolve https://github.com/openshift-cnv/cnv-ci/issues/77

### CODE REVIEW

**Comment by rabin-io** [comment]
@tiraboschi I see alot of this message is in the log,

```json
{"component":"virt-launcher","level":"error","msg":"unsupported configuration: Emulator '/usr/libexec/qemu-kvm' does not support machine type 'pc-q35-2.7'","pos":"qemuValidateDomainDef:1277","subcomponent":"libvirt","thread":"32","timestamp":"2023-10-17T18:30:29.671000Z"}
```

**Comment by tiraboschi** [comment]
> @tiraboschi I see alot of this message is in the log,

Trying with a fresher 4.14. compose.

**Pull request merged**
