### PR TITLE
Optionally deploy and upgrade from production

### PR DESCRIPTION
**Pull request by tiraboschi**
Enhance the deploy and upgrade scripts
so that they can also be used
to deploy and upgrade using only
the production index image.

Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>

### CODE REVIEW

**Comment by tiraboschi** [comment]
/hold
merge this only when we successfully tested it also with PRODUCTION_RELEASE=false

**Comment by orenc1** [comment]
4.8-e2e-upgrade - azure bootstrap error
/test 4.8-e2e-upgrade 
4.7-e2e-upgrade - same error as before

/override 4.8-e2e-deploy

**Comment by tiraboschi** [comment]
ci/prow/4.9-e2e-upgrade is failing because CNV 4.9.0 candidate bundle was replacing 4.8.0 while in production we already have 4.8.1; other than this which is a real bug on the bundle we can merge
/override 4.9-e2e-upgrade

**Review by orenc1 — APPROVED** [review]

**Pull request merged**
